# Generated by Django 4.2.16 on 2024-10-11 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hirers', '0006_alter_hirer_email_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255, null=True)),
                ('description', models.TextField()),
                ('salary', models.IntegerField()),
            ],
        ),
    ]
