# Generated by Django 4.2.16 on 2024-10-12 00:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Hirers', '0007_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='posted_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
