# Generated by Django 4.2.16 on 2024-10-12 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hirers', '0008_job_posted_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='salary',
            new_name='pay',
        ),
    ]
