# Generated by Django 4.2.16 on 2024-10-13 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hirers', '0009_rename_salary_job_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='hirer_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
